version: 2
jobs:
  build:
    working_directory: ~/forum_api
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          - RAILS_ENV=test
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - RACK_ENV=test
      - image: circleci/postgres:9.4.12-alpine
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=db_name
    steps:
      - checkout
      - restore_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results